sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: fCeKWByESKObF3cVuzaGM251Ej9DuX8lNjgZxQAMrzyhOi9nstxWLdHvATzw24wMvxvJ+LJN/fu0pMbmSCYzp4hYotYsdnmBLMoiako0I4utvuOYSTiht0tIITVJ9wgoxPZ8tne7A4cBN2qLOYD4MvF8rsyIs0WE/jkNkuS8vGzRvXETZgVC9xVIBFxLP1RRMtyZvkgvEsUsRDgpk/65mwOkeCuSq85TTXso0bdWqZFo6tw9+FYKLMzxM406JyBTX7kCsM1pfb18qSs5ya6wOMLgNKM8c1tPSj2w+SAgoCSXBNy8bUOLrsgOpq8JLv/XPUrqw+bZgn+p/l/w/bzINyYNEP7oXkRAt3mecVvcSnltT3ll4TK/deykWFv9+z2iwFhap6LnSewYrIWrinRIhc4uL1O3CAQQutPiTYUDk9rP0trkJUOB4G2pWo5qJ/E7y5lZyKeKdpESYcb46i95S0dw2wJozy0XhoPcaDLvTh29nEF6OiZhcV7RCyWBwJREK69i3m/5lX3+qM/2Ikj/WBQ/Fm9zsyqmeTycsKfyNP+x3/pjCPS6gW+xuutWSgy2ZxCrxBGwLPYpC7+0TZjwesVTxHCg2CsAz51pO6shdSlxJA9ZZ2ROzDNIhkJCJeCMMcSYoH0soTM4QWVyAKByMC/XZ8JJuDz96NBUXe+b2Pw=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Indian-Why-Stories--Sparks-from-War-Eagle-s-Lodge-Fire_606
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy